name: PandoraLimits
main: me.DawnBudgie.pandoralimits.PandoraLimits
version: 2.0
description: This plugin provides basic limiting to worldedit on a per-group basis, as determined by PEX.
author: DawnBudgie