name: PandoraLimits
main: me.DawnBudgie.PandoraLimits.PandoraLimits
version: 1.0
description: This plugin provides basic limiting to worldedit on a per-group basis, as determined by PEX.
author: DawnBudgie
